# Generated by Django 4.0.4 on 2022-05-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
